name: Compile

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

  workflow_dispatch:

jobs:
  
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.0.0

      - name: Compile x64
        run: dotnet build Development/StartingItemsGUI.csproj -a x64 --nologo
